# YAML instructions to create 2 datasets: "norm20" and "cars"
my_datasets = function(){

  # Initialize YAML instructions to create the "norm20" dataset
  fields = list(
    sources = "code.R",
    targets = list(
      all = list(depends = "norm20.rds")
    )
  )

  # Add the rule to generate the data
  fields$targets[["norm20.rds"]] = 
    list(command = "my_norm(file = \"norm20.rds\", size = 20)")

  # Turn the list into a YAML file for remake
  write_step(fields, "norm20.yml")
 
  # Similarly, write instructions to create the "cars" dataset
  fields = list(
    sources = "code.R",
    targets = list(
      all = list(depends = "cars.rds")
    )
  )
  fields$targets[["cars.rds"]] =
    list(command = "my_cars(file = \"cars.rds\")")
  write_step(fields, "cars.yml")
}

# YAML instructions to analyze each dataset with the ordinary_least_squares and
# use_rpart functions, then compute predictions from each fitted model.
my_analyses = function(){

  # Make a YAML instruction set for each dataset and each method of analysis
  for(dataset in c("norm20", "cars"))
  for(analyzer in c("my_ols", "my_rpart")){ 

    # Name of the analysis
    analysis = paste(dataset, analyzer, sep = "_")

    # paths to important files
    dataset_file = paste0(dataset, ".rds")
    analysis_object = paste0(analysis, "_analysis")
    summary_file = paste0(analysis, "_summary.rds")

    # Initialize the list of YAML fields    
    fields = list(
      sources = "code.R",
      targets = list(
        all = list(depends = summary_file)
      )
    )

    # Add a rule to analyze the data
    fields$targets[[analysis_object]] = 
      list(command = paste0(analyzer, "(\"", dataset, ".rds\")"))

    # Add a rule to summarize the analysis
    fields$targets[[summary_file]] = 
      list(command = paste0("my_predict(", analysis_object, ", \"", summary_file, "\")"))

    # Write the YAML file
    write_step(fields, paste0("", analysis, ".yml"))
  }
}

# Make a plot using a couple summaries of the analysis
my_plot = function(){

  # YAML fields for remake
  fields = list(
    sources = "code.R",
    targets = list(
      all = list(depends = "my_plot.pdf"),
      my_plot.pdf = list(
        command = "my_scatter(\"cars_my_ols_summary.rds\", \"cars_my_rpart_summary.rds\")",
        plot = "TRUE"
      )
    )
  )

  # write the YAML file
  write_step(fields, "my_plot.yml")
}

# generate the YAML files for remake
library(workflowHelper)
my_datasets()
my_analyses()
my_plot()

# Organize the steps of the workflow into sequential stages, each having parallel steps.
# The YAML files listed should have already been generated by the code above.
my_stages = list(
  dataset_stage = c(
    "cars.yml",
    "norm20.yml"
  ),
  analysis_and_summary_stage = c(
    "cars_my_ols.yml",
    "cars_my_rpart.yml",
    "norm20_my_ols.yml",
    "norm20_my_rpart.yml"
  ),
  plotting_stage = "my_plot.yml"
)

# Write the Makefile that organizes the workflow into stages
write_workflow(my_stages)

# Next, try running `make` or `make -j 4` from the command line.
# Run `make clean` to get rid of everything generated except the YAML files.
