# library(testthat); library(parallelRemake); 
context("run_example_parallelRemake")
source("utils.R")

test_that("Example runs as expected", {
  testwd("example-ok")
  initial_files = list.files()
  data(mtcars)
  expect_equal(list.files(), character(0))
  run_example_parallelRemake()
  files = c("code.R", "Makefile", "plot.pdf", "remake.yml")
  expect_true(all(files %in% list.files()))
  expect_true(all(recallable() == c("mtcars", "random")))
  expect_equal(recall("mtcars"), mtcars)
  expect_equal(dim(recall("random")), c(32, 1))
  expect_true(all(is.finite(as.matrix(recall("random")))))
  expect_true(file.exists(".remake"))
  clean_example_parallelRemake()
  expect_false(file.exists(".remake"))
  expect_equal(list.files(), initial_files)
  testrm("example-ok")
})
