#' @title Function \code{write_example}
#' @description Write the files \code{code.R} and \code{remake.yml} for the example.
#' @export
write_example_parallelRemake = function(){
  for(file in c("code.R", "remake.yml")){
    path = system.file("example", file, package = "parallelRemake")
    if (!file.exists(path)) stop("File ", file, 
      " is missing from installed package parallelRemake.", call.=FALSE)
    contents = readLines(path)
    write(contents, file)
  }
}


#' @title Function \code{setup_example}
#' @description Write the files \code{code.R} and \code{remake.yml} for the example. 
#' and then write the Makefile.
#' @export
setup_example_parallelRemake = function(){
  write_example_parallelRemake()
  write_makefile()
}

#' @title Function \code{run_example}
#' @description Run the whole example: generate the \code{remake} file,
#' then generate the master \code{Makefile} to run the targets in parallel,
#' and then run \code{make} to run the workflow in parallel.
#' @export
#' @param intern Argument to system, option to capture output.
run_example_parallelRemake = function(intern = F){
  setup_example_parallelRemake()
  system("make -j 4 2>&1", intern = intern)
}

#' @title Function \code{clean_example}
#' @description Clean up files generated by the package example.
#' @export
#' @param intern Argument to system, option to capture output.
clean_example_parallelRemake = function(intern = F){
  system("make clean 2>&1", intern = intern)
  unlink(c("code.R", "remake.yml", "Makefile"))
}

