#' @title Function \code{write_example_parallelRemake}
#' @description Writes the files \code{code.R} and \code{remake.yml} 
#' for the package example.
#' @export
write_example_parallelRemake = function(){
  dir = system.file("example", package = "parallelRemake")
  for(file in list.files(dir)){
    path = system.file("example", file, package = "parallelRemake")
    if (!file.exists(path)) stop("File ", file, 
      " is missing from installed package parallelRemake.", call.=FALSE)
    contents = readLines(path)
    write(contents, file)
  }
}

#' @title Function \code{setup_example_parallelRemake}
#' @description Writes the files \code{code.R} and \code{remake.yml} for 
#' the package example and then produces the Makefile.
#' @export
setup_example_parallelRemake = function(){
  write_example_parallelRemake()
  write_makefile()
}

#' @title Function \code{run_example_parallelRemake}
#' @description Runs the whole package example from start to finish.
#' Generates the files \code{code.R} and \code{remake.yml}, produces the 
#' Makefile, and then runs \code{make} to execute the workflow in parallel.
#' @export
run_example_parallelRemake = function(){
  setup_example_parallelRemake()
  system("make -j 2")
}

#' @title Function \code{clean_example_parallelRemake}
#' @description Cleans up files generated by the package example.
#' @export
clean_example_parallelRemake = function(){
  system("make clean")
  unlink(c("code.R", "remake.yml", "Makefile"))
}

