#' @include clean_stages.R
NULL

#' @title Function \code{write_workflow}
#' @description Takes a collection of \code{remake} YAML files (github.com/richfitz/remake)
#' and creates an overarching Makefile to run them all in parallelizable stages 
#' (with \code{make -j} on the command line).
#' @export
#' @param file Path to output Makefile.
write_workflow = function(stages, file = "Makefile"){
  stages = clean_stages(stages)
  sink(file)
  cat("# Generated by workflowHelper::workflow() on", as.character(Sys.time()), "\n\n")
  cat(".PHONY: all clean", names(stages), unlist(stages), "\n\n")
  cat("all: ", names(stages)[length(stages)], "\n\n")

  for(i in length(stages):1){
    previous = ifelse(i == 1, "", names(stages)[i - 1])
    cat(names(stages)[i], ":", previous, stages[[i]], "\n\n")
  }

  cat("clean:\n")
  remakes = unlist(stages)
  for(i in 1:length(remakes))
    cat("\tRscript -e \'remake::make(\"clean\", remake_file = \"", remakes[i], ".yml\")\'\n", sep = "")
  cat("\n")

  for(i in 1:length(remakes))
    cat(remakes[i], ":\n\tRscript -e \'remake::make(remake_file = \"", 
      remakes[i], ".yml\")\'\n\n", sep = "")
  sink()
}
