#' @title Function \code{write_makefile}
#' @description Write a master Makefile to run \code{remake} targets in parallel.
#' @export
#' @param makefile name of Makefile to write.
#' @param remakefiles Character vector of paths to input \code{remake} files.
#' @param begin Character vector of lines to prepend to the Makefile.
#' @param clean Character vector of commands to add to the \code{clean} rule.
write_makefile = function(makefile = "Makefile", remakefiles = "remake.yml", begin = NULL, clean = NULL){

# For debugging:
# library(stringr); library(parallelRemake); example_remake_file(); remakefiles = "remake.yml"; makefile = "Makefile"; begin = c("# Additional lines", "#!/bin/bash"); clean = c("rm -rf file1", "rm -rf file2")

# library(stringr); library(parallelRemake); setwd("~/Desktop/baad"); remakefiles = "remake.yml"; makefile = "Makefile"; begin = c("# Additional lines", "#!/bin/bash"); clean = c("rm -rf file1", "rm -rf file2")

  if(length(remakefiles) > 1 || length(yaml_read(remakefiles[1])$include) > 0){
    remakefile = collate_yaml(remakefiles)
  } else {
    remakefile = remakefiles
  }

  remake_data = yaml_read(remakefile)
  targets = remake_data$targets

  sink(makefile)
  cat("# Generated by parallelRemake::write_makefile() on", as.character(Sys.time()), "\n\n")
  if(!is.null(begin)){
    cat(begin, sep = "\n")
    cat("\n")
  }

  cat(".PHONY:", names(targets), "clean\n\n")
  
  for(name in names(targets)){
    cat(name, ": ", sep = "")
    target = targets[[name]]
    dep = unique(c(unlist(target$depends), parse_command(target$command)$depends))
    dep = dep[dep != "target_name"] # "target_name" is a keyword in remake.
    cat(dep, "\n")
    if("command" %in% names(target)){
      cat("\tRscript -e \'remake::make(\"", name, "\", remake_file = \"", 
          remakefile, "\")\'\n", sep = "")
    }
    cat("\n")
  }

  cat("clean:\n\tRscript -e \'remake::make(\"clean\", remake_file = \"", 
          remakefile, "\")\'\n", sep = "")
  for(rule in clean) cat("\t", str_trim(rule), "\n", sep = "")

  sink()
}
