#' @include clean_stages.R
NULL

#' @title Function \code{write_makefile}
#' @description Takes a collection of \code{remake} YAML files (github.com/richfitz/remake)
#' and creates an overarching Makefile to run them all in parallelizable stages 
#' (with \code{make -j} on the command line).
#' @export
#' @param stages List of character vectors. Organizes the steps of a 
#' workflow into parallelizable stages. Each character string is a 
#' path to a \code{remake}/YAML file encoding a step in the workflow.
#' The ".yml" file extension is optional.
#' @param file Path to output Makefile.
write_makefile = function(stages, file = "Makefile"){
  stages = clean_stages(stages)
  sink(file)
  cat("# Generated by parallelRemake::write_makefile() on", as.character(Sys.time()), "\n\n")
  cat(".PHONY: all clean clean_make clean_yaml clean_all", names(stages), unlist(stages), "\n\n")
  cat("all: ", names(stages)[length(stages)], "\n\n")

  for(i in length(stages):1){
    previous = ifelse(i == 1, "", names(stages)[i - 1])
    cat(names(stages)[i], ":", previous, stages[[i]], "\n\n")
  }

  yaml = unlist(stages)
  for(i in 1:length(yaml))
    cat(yaml[i], ":\n\tRscript -e \'remake::make(remake_file = \"", 
      yaml[i], ".yml\")\'\n\n", sep = "")

  cat("clean_all: clean clean_yaml clean_makefile\n\n")

  cat("clean:\n")
  for(i in 1:length(yaml))
    cat("\tRscript -e \'remake::make(\"clean\", remake_file = \"", yaml[i], ".yml\")\'\n", sep = "")
  cat("\n")

  cat("clean_yaml:\n")
  for(i in 1:length(yaml))
    cat("\trm -f ", yaml[i], ".yml\n", sep = "")
  cat("\n")

  cat(paste0("clean_makefile:\n\trm -f ", file, "\n"))

  sink()
}
