#' @include single_field.R
NULL

#' @title Function \code{write_yaml}
#' @description Creates a \code{remake} YAML file (github.com/richfitz/remake) to define 
#' a sequential step within a parallelized stage of a workflow. See the README at 
#' github.com/wlandau/parallelRemake for details.
#' @export
#' @param fields a nested list defnining the fields of the \code{remake} YAML file
#' @param file Path to output remakefile.
write_yaml = function(fields, file = "remake.yml"){
  if(!length(fields)) stop("no YAML fields. Nothing to do.")
  sink(file)
  cat("# Generated by parallelRemake::write_yaml() on", as.character(Sys.time()), "\n\n")
  single_field(fields)
  sink()
}
