#' @include single_field.R
NULL

#' @title Function \code{write_step}
#' @description Creates a \code{remake} YAML file (github.com/richfitz/remake) to define 
#' a sequential step within a parallelized stage of a workflow. See the README at 
#' github.com/wlandau/workflowHelper for details.
#' @export
#' @param fields a nested list defnining the fields of the \code{remake} YAML file
#' @param file Path to output remakefile.
write_step = function(fields, file = "remake.yml"){
  sink(file)
  cat("# Generated by write_step() on", as.character(Sys.time()), "\n\n")
  single_field(fields)
  sink()
}
